### PR TITLE
update survery form

### PR DESCRIPTION
**Pull request by songhany**
Modify EndModal.js by adding Survey Questions into form

### CODE REVIEW

**Comment by ceiphr** [comment]
Awesome! The form looks good, but the PR seems to have two issues:

1. You need to add the import for `Select`: https://mantine.dev/core/select/
2. I'm unsure why, but the commit changes every line in a way I'm sure what changed

Please fix these two issues when you can. Alternatively, I can copy your form implementation and commit it directly to the main branch if that works for you.

**Comment by songhany** [comment]
Yeah, copy it and commit it directly to main. Actually, I am also confused the commit changed every line of code, it seems because I open this project in wsl2, when i open it in wsl2, it shows modification to every line of code. I have node version problem in my original windows environment with node@16.

**Comment by ceiphr** [comment]
No worries! Thank you for doing this, it looks great!

I'll get it committed to main now.

**Comment by ceiphr** [comment]
Added!

**Pull request closed without merging**
